name: Upload RHCSA Content on 19 Sep 2024

on:
  schedule:
    - cron: "0 7 19 9 *"  # Run at 7 AM on 19 September 2024

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'Gaurav Mathur'
        git config --global user.email 'youremail@example.com'

    - name: Commit changes
      run: |
        git add rhcsa/rhcsa.md
        git commit -m "Added archive files content"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
